#!/bin/bash
cd build
#cmake .. -DSAF_PERFORMANCE_LIB=SAF_USE_INTEL_MKL_ILP64 -DSAF_BUILD_EXAMPLES=0 -DSAF_BUILD_TESTS=0
cmake .. -DSAF_PERFORMANCE_LIB=SAF_USE_OPEN_BLAS_AND_LAPACKE -DSAF_BUILD_EXAMPLES=0 -DSAF_BUILD_TESTS=0
make
